image: Visual Studio 2017
branches:
  only:
    - master
environment:
  NUGET_KEY:
    secure: Uhan5YIuSa14YXdgATOaAcUqNna1FgbgkFTjmlyYvdnJ15z7OMnp+Kq9ndd5iTnQ
  nugetkey:
    secure: Uhan5YIuSa14YXdgATOaAcUqNna1FgbgkFTjmlyYvdnJ15z7OMnp+Kq9ndd5iTnQ
init:
  - git config --global core.autocrlf input
build_script:
  - cmd: build.cmd All
test: off
version: 0.0.1.{build}
artifacts:
  - path: 'nupkg\*.nupkg'
    type: NuGetPackage
nuget:
  account_feed: false
  project_feed: true