// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hopac.IO")>]
[<assembly: AssemblyProductAttribute("Hopac.IO")>]
[<assembly: AssemblyDescriptionAttribute("Extensions for standard IO operations with Hopac Jobs")>]
[<assembly: AssemblyVersionAttribute("1.4.2")>]
[<assembly: AssemblyFileVersionAttribute("1.4.2")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hopac.IO"
    let [<Literal>] AssemblyProduct = "Hopac.IO"
    let [<Literal>] AssemblyDescription = "Extensions for standard IO operations with Hopac Jobs"
    let [<Literal>] AssemblyVersion = "1.4.2"
    let [<Literal>] AssemblyFileVersion = "1.4.2"
    let [<Literal>] AssemblyConfiguration = "Release"
